language: csharp
solution: SCS_Logbook.sln
install:
  - nuget restore SCS_Logbook.sln
script:
  - msbuild /p:Configuration=Release SCS_Logbook/SCS_Logbook.csproj

deploy:
  provider: script
  script: bash DB/flyway migrate
  on:
    branch: develop